### ISSUE TITLE
harmonize font usage across site

### ISSUE THREAD

**Issue by JoernT** [eXistSolutions/sarit-pm#1]
The old site has a different layout than the new site. The latter is based upon TEI PM and outputs different markup. 

For the actual indian texts a special font must be used that support the devanagari symbols.

For the non-dynamic text an appropriate font shoud be used (currently it defaults to the material design font roboto. 

Also the font sizes need to be harmonized.

**Comment by wolfgangmm** [comment]
Basically Siddhanta has to be used for all text blocks. For labels which will never use Sanskrit we can stick to the roboto font.

**Comment by wolfgangmm** [comment]
As I understand the customer, they would like all text (apart from menu and button labels I guess) to be rendered with Siddhanta. In particular the file header is now still sans-serif,e.g.

http://showcases.exist-db.org/exist/apps/sarit-pm/works/kautalyarthasastra.xml?view=page

**Comment by plutonik-a** [comment]
### Smaller base font-size (1.5rem), "Siddhanta" as default font-family

<img width="1143" alt="bildschirmfoto 2016-06-09 um 15 37 55" src="https://cloud.githubusercontent.com/assets/1157669/15931569/92552408-2e58-11e6-99e6-f0ea8cdc7583.png">

---

<img width="931" alt="bildschirmfoto 2016-06-09 um 15 40 13" src="https://cloud.githubusercontent.com/assets/1157669/15931616/c991fb4e-2e58-11e6-8962-e704322e4dd8.png">

---

### File header with "Siddhanta"

<img width="998" alt="bildschirmfoto 2016-06-09 um 15 38 28" src="https://cloud.githubusercontent.com/assets/1157669/15931626/d4aa6764-2e58-11e6-9091-07e3373cc945.png">

---

### Harmonic font-sizes/proportions between text and different headings

<img width="675" alt="bildschirmfoto 2016-06-09 um 15 47 16" src="https://cloud.githubusercontent.com/assets/1157669/15931800/7ba7974e-2e59-11e6-9b8d-c5cea79e86f3.png">

---

<img width="672" alt="bildschirmfoto 2016-06-09 um 15 38 11" src="https://cloud.githubusercontent.com/assets/1157669/15931656/f939aafe-2e58-11e6-8e7a-1f95da55ff00.png">

---

### Labels in sans font

<img width="420" alt="bildschirmfoto 2016-06-09 um 15 40 02" src="https://cloud.githubusercontent.com/assets/1157669/15931872/bcafda8a-2e59-11e6-9a9e-0a751a7cee9d.png">

<img width="233" alt="bildschirmfoto 2016-06-09 um 15 49 30" src="https://cloud.githubusercontent.com/assets/1157669/15931886/cba5c306-2e59-11e6-86fc-4bfddf863bc6.png">

---

### Top menu with bold font and sans font-family

<img width="474" alt="bildschirmfoto 2016-06-09 um 15 37 37" src="https://cloud.githubusercontent.com/assets/1157669/15931926/f6c73344-2e59-11e6-8f1e-401b13ea0c68.png">
