### ISSUE TITLE
Hits in note-elements

### ISSUE THREAD

**Issue by JoernT** [eXistSolutions/sarit-pm#22]
When a word occurs in a <note>, clicking on the hit in the KWIC list leads you to the right passage but there is no way to find out that the hit is "hidden" in a note.
So the user might get the impression that the search engine is not working properly. Could this be improved?
Here is an example:
Hit 1 when looking for "tatraiva" (NGram search) in Pramāṇavārttikavṛtti takes you to this page http://sarit.indology.info/exist/apps/sarit/works/div_pvv.1.108.html?action=search#1.5.4.1.11.81.4 The hit is in the fourth note.

**Comment by wolfgangmm** [comment]
Fixed because footnotes are now shown on the bottom of the page and the link will point there.
