### ISSUE TITLE
Text flow in search results

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/sarit-pm#27]
For some types of searches, the displayed results break out and extend over the search box. For example, try an ngram search for "pusa.*it":

http://showcases.exist-db.org/exist/apps/sarit-pm/works/search.html?query=pusa.*it&field=text&query-scripts=all&index=ngram&tei-target=tei-text&work-authors=all&query-scope=narrow&bool=new

![image](https://cloud.githubusercontent.com/assets/607433/14980498/4c2b1a60-1129-11e6-9547-6c10623674ce.png)

**Comment by plutonik-a** [comment]
@wolfgangmm 
How can I perform a search request on my local machine?
Whatever I try to search, the result is 

```
HTTP ERROR 500
Problem accessing /exist/apps/sarit-pm/works/search.html. Reason:
Server Error
Caused by:
javax.servlet.ServletException: An unknown error occurred: com/ibm/icu/text/Transliterator ...
```
