### ISSUE TITLE
adapt new site css to old site css

### ISSUE THREAD

**Issue by JoernT** [eXistSolutions/sarit-pm#4]
the app in general needs to be ported CSS-wise. The new app is based upon TEI PM app builder and varies from the old one. The site does not need to be reconstructed in detail but should have a similar layout in general. So the adaptions would be in fonts, font-sizes, (optionally) colors and spacings.

In certain areas changing lists to tables or similar might make sense. Improvements can always be proposed so no _strict_ aherence to the old site is needed.

**Comment by plutonik-a** [comment]
Fixed within issue https://github.com/eXistSolutions/sarit-pm/issues/9 and partly https://github.com/eXistSolutions/sarit-pm/issues/2
