### ISSUE TITLE
Document list should be output as table

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/sarit-pm#5]
Is is rendered via TEI PM, so the change has to be done in the ODD.

![image](https://cloud.githubusercontent.com/assets/607433/14790250/bd2a6c6c-0b10-11e6-8199-30ac713fa5c6.png)

Note that each document also has a checkbox to limit search to it.

**Comment by plutonik-a** [comment]
Related: https://github.com/eXistSolutions/sarit-pm/issues/15
